development:
  app_id: 186636844757828
  app_secret: 0526e24efe5ea9e689d22f396811fcbd
  canvas_url: http://apps.facebook.com/kimo_test/
  access_token: AAACpvsbVc0QBADqfb4ue4ZA2ZBJIij01tlyLDcZA12BvAA0kQerss44ZABleQVSV4owTSOTfUD1aoCHZCX3JuD5YQdANL4wfNAbRHg8pxYAZDZD
    
test:
  app_id: 186636844757828
  app_secret: 0526e24efe5ea9e689d22f396811fcbd
  canvas_url: http://apps.facebook.com/kimo_test/
  access_token: AAACpvsbVc0QBADqfb4ue4ZA2ZBJIij01tlyLDcZA12BvAA0kQerss44ZABleQVSV4owTSOTfUD1aoCHZCX3JuD5YQdANL4wfNAbRHg8pxYAZDZD
      
staging:
  app_id: 186636844757828
  app_secret: 0526e24efe5ea9e689d22f396811fcbd
  canvas_url: http://apps.facebook.com/kimo_test/
  access_token: AAACpvsbVc0QBADqfb4ue4ZA2ZBJIij01tlyLDcZA12BvAA0kQerss44ZABleQVSV4owTSOTfUD1aoCHZCX3JuD5YQdANL4wfNAbRHg8pxYAZDZD

production:
  app_id: 186636844757828
  app_secret: 0526e24efe5ea9e689d22f396811fcbd
  canvas_url: http://apps.facebook.com/kimo_test/
  access_token: AAACpvsbVc0QBADqfb4ue4ZA2ZBJIij01tlyLDcZA12BvAA0kQerss44ZABleQVSV4owTSOTfUD1aoCHZCX3JuD5YQdANL4wfNAbRHg8pxYAZDZD